var i = 0;

while (i <= 10) {
  if (i == 0) print "holy";
  else if (i == 1) print "shit";
  else if (i == 2) print "my";
  else if (i == 3) print "dudes";
  else if (i == 4) print "i";
  else if (i == 5) print "have";
  else if (i == 6) print "control";
  else if (i == 7) print "flow";
  else if (i == 8) print "des";
  else if (i == 9) print "pa";
  else if (i == 10) print "ci";
  else if (i == 11) print "to";
  
  i = i + 1;
}