import '../abs.dart';
import '../division.dart';
import '../exponentiation.dart';
import '../log.dart';
import '../multiplication.dart';
import '../number.dart';
import '../negative.dart';
import '../root.dart';
import '../sgn.dart';
import '../sum.dart';
import '../inverse_hyperbolic/arcosh.dart';
import '../inverse_hyperbolic/arcsch.dart';
import '../inverse_hyperbolic/arctgh.dart';
import '../inverse_hyperbolic/arsech.dart';
import '../inverse_hyperbolic/arsinh.dart';
import '../inverse_hyperbolic/artanh.dart';
import '../inverse_trig/arccos.dart';
import '../inverse_trig/arccsc.dart';
import '../inverse_trig/arcctg.dart';
import '../inverse_trig/arcsec.dart';
import '../inverse_trig/arcsin.dart';
import '../inverse_trig/arctan.dart';
import '../trig/cos.dart';
import '../trig/csc.dart';
import '../trig/ctg.dart';
import '../trig/sec.dart';
import '../trig/sin.dart';
import '../trig/tan.dart';
import '../hyperbolic/cosh.dart';
import '../hyperbolic/csch.dart';
import '../hyperbolic/ctgh.dart';
import '../hyperbolic/sech.dart';
import '../hyperbolic/sinh.dart';
import '../hyperbolic/tanh.dart';
import '../variable.dart';

abstract class FunctionVisitor<ReturnType> {
  const FunctionVisitor();
  ReturnType visitAbs(AbsoluteValue f);
  ReturnType visitDivision(Division f);
  ReturnType visitExponentiation(Exponentiation f);
  ReturnType visitCosH(CosH f);
  ReturnType visitCscH(CscH f);
  ReturnType visitCtgH(CtgH f);
  ReturnType visitSecH(SecH f);
  ReturnType visitSinH(SinH f);
  ReturnType visitTanH(TanH f);
  ReturnType visitArCosH(ArCosH f);
  ReturnType visitArCscH(ArCscH f);
  ReturnType visitArCtgH(ArCtgH f);
  ReturnType visitArSecH(ArSecH f);
  ReturnType visitArSinH(ArSinH f);
  ReturnType visitArTanH(ArTanH f);
  ReturnType visitArcCos(ArcCos f);
  ReturnType visitArcCsc(ArcCsc f);
  ReturnType visitArcCtg(ArcCtg f);
  ReturnType visitArcSec(ArcSec f);
  ReturnType visitArcSin(ArcSin f);
  ReturnType visitArcTan(ArcTan f);
  ReturnType visitLog(Log f);
  ReturnType visitMultiplication(Multiplication f);
  ReturnType visitNegative(Negative f);
  ReturnType visitNumber(Number f);
  ReturnType visitRoot(Root f);
  ReturnType visitSignum(Signum f);
  ReturnType visitSum(Sum f);
  ReturnType visitCos(Cos f);
  ReturnType visitCsc(Csc f);
  ReturnType visitCtg(Ctg f);
  ReturnType visitSec(Sec f);
  ReturnType visitSin(Sin f);
  ReturnType visitTan(Tan f);
  ReturnType visitVariable(Variable f);
}
