let A = {1, 2, 3, 4}

let B = (0, 5)

let C = {x| x == 5}

let D = {| x^2 == 2}

print A
print B
print C
print D

//print A contained B - this also works, but using the unicode symbols is prettier
print A ⊂ B

//print 2.5 belongs A
print 2.5 ∈ A

//print 2.5 belongs B
print 2.5 ∈ B

//print A union B
print A ∪ B

//print A intersection B
print A ∩ B

//no pretty symbol for this one :(
print A disjoined C

print C'

print A\B

print {x| cos(4)*x > e^2}